version: "3.8"
include:
  - './minio/docker-compose.yml'
  - './traefik/docker-compose.yml'
networks:
  backend:
    name: backend
    external: true
  frontend:
    name: frontend
    external: true
