version: "3.8"

services:
  traefik:
    image: "traefik:v2.10"
    container_name: traefik
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./conf:/traefik"
      - "${SRV_VOLUMES_PATH}/letsencrypt:/letsencrypt"
    environment:
      - SRV_ENV
      - BASE_DOMAIN
      - CLOUDFLARE_EMAIL
      - CLOUDFLARE_API_KEY
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    networks:
      - backend
      - frontend
